import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#eef7fb',
  },
  content: {
    padding: 16,
    paddingBottom: 40,
    gap: 14,
  },
  heroCard: {
    backgroundColor: '#082f49',
    borderRadius: 18,
    padding: 18,
    gap: 6,
  },
  title: {
    fontSize: 30,
    fontWeight: '700',
    color: '#fff',
  },
  subtitle: {
    color: '#dbeafe',
    fontSize: 14,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: '#d5e7f3',
  },
  cardTitle: {
    fontWeight: '700',
    color: '#0f172a',
    fontSize: 16,
    fontFamily: 'Georgia',
  },
  helperText: {
    color: '#475569',
  },
  pillWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    borderWidth: 1,
    borderColor: '#bae6fd',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: '#f0f9ff',
  },
  pillActive: {
    backgroundColor: '#0369a1',
    borderColor: '#0369a1',
  },
  pillText: {
    color: '#0c4a6e',
    fontSize: 12,
    fontWeight: '600',
  },
  pillTextActive: {
    color: '#fff',
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  statsStack: {
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#d5e7f3',
    gap: 6,
  },
  statLabel: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '600',
  },
  statValue: {
    color: '#0f172a',
    fontSize: 24,
    fontWeight: '700',
  },
  progressCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#d5e7f3',
    gap: 6,
  },
  rateCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#d5e7f3',
    gap: 6,
  },
  rateValue: {
    color: '#0f172a',
    fontSize: 22,
    fontWeight: '700',
  },
  progressValue: {
    color: '#0f172a',
    fontSize: 22,
    fontWeight: '700',
  },
  progressSubtext: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '600',
  },
  chartCard: {
    backgroundColor: '#f8fbff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dbeafe',
    padding: 12,
    gap: 10,
    overflow: 'hidden',
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metricCard: {
    flexBasis: '48%',
    backgroundColor: '#f8fbff',
    borderWidth: 1,
    borderColor: '#dbeafe',
    borderRadius: 10,
    padding: 10,
    gap: 4,
  },
  metricLabel: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metricValue: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '700',
  },
  metricSubLabel: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '600',
  },
  chartTitle: {
    color: '#0c4a6e',
    fontWeight: '700',
    fontFamily: 'Georgia',
  },
  chartTabs: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
    marginBottom: 12,
  },
  chartTab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#bae6fd',
    backgroundColor: '#f8fbff',
  },
  chartTabActive: {
    backgroundColor: '#0369a1',
    borderColor: '#0369a1',
  },
  chartTabText: {
    color: '#0c4a6e',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Georgia',
  },
  chartTabTextActive: {
    color: '#fff',
  },
  breakdownList: {
    gap: 8,
  },
  breakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#fff',
  },
  breakdownMonth: {
    color: '#0f172a',
    fontWeight: '600',
  },
  breakdownAmount: {
    color: '#0369a1',
    fontWeight: '700',
  },
  chartValueBadgeContainer: {
    width: 132,
    height: 60,
    marginLeft: -57,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  chartValueBadge: {
    backgroundColor: '#0f172a',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#334155',
    minWidth: 110,
  },
  chartValueBadgeMonth: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 2,
  },
  chartValueBadgeText: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '700',
  },
  yearList: {
    gap: 8,
  },
  yearRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 12,
  },
  yearLabel: {
    color: '#0f172a',
    fontWeight: '700',
  },
  yearValue: {
    color: '#0369a1',
    fontWeight: '700',
  },
  historyScroll: {
    maxHeight: 440,
  },
  historyScrollContent: {
    gap: 8,
  },
  eventRow: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 12,
    gap: 4,
  },
  eventAmount: {
    color: '#0369a1',
    fontWeight: '700',
    fontSize: 16,
    fontFamily: 'Georgia',
  },
  eventGoalName: {
    color: '#0f172a',
    fontWeight: '700',
    marginBottom: 2,
    fontFamily: 'Georgia',
  },
  eventDate: {
    color: '#0f172a',
    fontWeight: '600',
    fontFamily: 'Georgia',
  },
  eventCreated: {
    color: '#64748b',
    fontSize: 12,
    fontFamily: 'Georgia',
  },
  emptyState: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    gap: 10,
  },
  emptyTitle: {
    color: '#0f172a',
    fontWeight: '700',
    fontSize: 20,
  },
  emptyText: {
    color: '#475569',
  },
});
